Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CHMIS.BLL;
using CHMIS.Models;
using CHMIS.ModelView;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Syncfusion.Drawing;
using Syncfusion.XlsIO;
using Syncfusion.DocIO;
using Syncfusion.DocIO.DLS;
using Syncfusion.JavaScript.DataSources;
using Syncfusion.Linq;
using System.Collections;
using Microsoft.AspNetCore.Http;
using System.Globalization;
using Microsoft.EntityFrameworkCore;

namespace CHMIS.Controllers
{
    public class ReportsController : Controller
    {
        private CHMISContext _context;
        private IWebHostEnvironment hostingEnv;
        private IUserService userInfor;
        private IHttpContextAccessor httpContext;

        public ReportsController(CHMISContext Context, IWebHostEnvironment env, IUserService _userinfo, IHttpContextAccessor _httpContext)
        {
            this._context = Context;
            this.hostingEnv = env;
            this.userInfor = _userinfo;
            this.httpContext = _httpContext;
        }
        public IActionResult SitRepReports()
        {
            ViewBag.division = _context.ACounty.ToList();
            return View();
        }

        public IActionResult CombinedSitRepReports()
        {
            ViewBag.division = _context.ACounty.ToList();
            return View();
        }

        //word document
        [HttpPost]
        public ActionResult WordExportSitRep(ReportsViewModel value)
        {
            //var data = _context.ViewReportSitRep.Where(x=>x.Division== value.Division && x.ReportingDate == value.StartDate).ToList();
            CultureInfo current = new CultureInfo("en-US");
            string format = "yyyy/MM/dd";
            DateTime _date = DateTime.Now;
            //IEnumerable data = null;
            DateTime edate = DateTime.Now;

            if (DateTime.TryParseExact(value.StartDate, format, current, DateTimeStyles.None, out _date))
            {
                edate = _date;
            }
            var data = _context.ViewReportSitRep.Where(o => o.ReportingDate.Value.Date == edate.Date && o.Division == value.Division).OrderBy(o => o.SitRepCategoryId).ToList();

            if (data.Count > 0)
            {

                var _division = "No Selected Division";// _context.ViewReportSitRep.FirstOrDefault(o => o.ReportingDate.Value.Date == edate.Date && o.Division == value.Division);
                var xdiv = _context.ViewReportSitRep.FirstOrDefault(o => o.ReportingDate.Value.Date == edate.Date && o.Division == value.Division);
                //var xdate = _context.ViewReportSitRep.FirstOrDefault(o => o.ReportingDate.Value.Date == edate.Date && o.Division == value.Division);

                if (xdiv != null)
                {
                    _division = xdiv.CountyName;
                }
                var _datatime = System.DateTime.Now.ToLongDateString();
                if (xdiv != null)
                {
                    _datatime = xdiv.ReportingDate.Value.ToLongDateString();
                }

                //Create a new document
                WordDocument document = new WordDocument();
                //Adding a new section to the document
                IWSection section = document.AddSection();

                //Sets page setup options for LandscapePageSetup.Orientation
                //section.PageSetup.Orientation = PageOrientation.Landscape;

                IWTable Headertable = section.HeadersFooters.Header.AddTable();
                Headertable.ResetCells(1, 1);
                WTableRow Headerrow = Headertable.Rows[0];

                //Headerrow.Height = 25f;
                //Adds a new paragraph to the cell
                IWParagraph HeadercellPara = Headerrow.Cells[0].AddParagraph();

                //string basePath = Server.MapPath("~/");
                string basePath = hostingEnv.WebRootPath;
                FileStream imageStream = new FileStream(basePath + @"/covidlog.png", FileMode.Open, FileAccess.Read);
                //System.Drawing.Image _image = System.Drawing.Image.FromStream(imageStream);
                HeadercellPara.AppendPicture(imageStream);

                Headerrow.Cells[0].CellFormat.Borders.BorderType = BorderStyle.None;
                Headerrow.Cells[0].CellFormat.Borders.Color = Syncfusion.Drawing.Color.FromArgb(255, 255, 255);
                HeadercellPara.ParagraphFormat.HorizontalAlignment = HorizontalAlignment.Center;

                //HeadercellPara.ParagraphFormat.HorizontalAlignment = HorizontalAlignment.Right;
                //Headerrow.Cells[0].Width = 350;

                // InsertFirstPageHeaderFooter(document, section);
                //Adding a new paragraph to the section
                IWParagraph paragraph = section.AddParagraph();


                #region Title Section
                //Adds a new table to the section
                IWTable table = section.Body.AddTable();
                table.ResetCells(2, 2);
                table.ApplyHorizontalMerge(0, 0, 1);
                table.ApplyHorizontalMerge(1, 0, 1);

                #region first row
                //Gets the table first row
                WTableRow row = table.Rows[0];
                row.Height = 25f;
                //Adds a new paragraph to the cell
                IWParagraph cellPara = row.Cells[0].AddParagraph();
                row.Cells[0].CellFormat.Borders.BorderType = BorderStyle.None;
                row.Cells[0].CellFormat.Borders.Color = Syncfusion.Drawing.Color.FromArgb(255, 255, 255);
                cellPara.ParagraphFormat.HorizontalAlignment = HorizontalAlignment.Center;
                //Appends the text
                string paraText = "KCCA COVID 19 RESPONSE SITUATION REPORT \n As at Date:  " + _datatime;// System.DateTime.Now.ToShortDateString() + "\n Time: " + System.DateTime.Now;
                IWTextRange titletxt = cellPara.AppendText(paraText);
                titletxt.CharacterFormat.FontName = "Times New Roman";
                //titletxt.CharacterFormat.TextColor = Syncfusion.Drawing.Color.FromArgb(192, 0, 0);
                titletxt.CharacterFormat.Bold = true;
                titletxt.CharacterFormat.FontSize = 16f;
                titletxt.CharacterFormat.AllCaps = false;
                //Adds a new paragraph to the next cell
                cellPara = row.Cells[1].AddParagraph();
                row.Cells[1].CellFormat.Borders.BorderType = BorderStyle.None;
                row.Cells[1].CellFormat.Borders.Color = Syncfusion.Drawing.Color.FromArgb(255, 255, 255);
                row.Cells[1].CellFormat.VerticalAlignment = VerticalAlignment.Middle;
                row.Cells[1].CellFormat.BackColor = Syncfusion.Drawing.Color.FromArgb(255, 255, 255);
                //Appends the text
                IWTextRange txt = cellPara.AppendText("");
                cellPara.ParagraphFormat.HorizontalAlignment = HorizontalAlignment.Center;
                row.Cells[0].Width = 350;
                row.Cells[1].Width = 150;
                #endregion first row

                #region Second row
                //Gets the table first row
                row = table.Rows[1];
                row.Height = 25f;
                //Adds a new paragraph to the cell
                cellPara = row.Cells[0].AddParagraph();
                row.Cells[0].CellFormat.Borders.BorderType = BorderStyle.None;
                row.Cells[0].CellFormat.Borders.Color = Syncfusion.Drawing.Color.FromArgb(255, 255, 255);
                cellPara.ParagraphFormat.HorizontalAlignment = HorizontalAlignment.Left;
                //Appends the text
                paraText = "\n KCCA COVID 19 Response Situation Report for : " + _division + " and Reporting date of: " + _datatime;
                titletxt = cellPara.AppendText(paraText);
                titletxt.CharacterFormat.FontName = "Times New Roman";
                titletxt.CharacterFormat.Bold = false;
                titletxt.CharacterFormat.FontSize = 11f;
                titletxt.CharacterFormat.AllCaps = false;
                //Adds a new paragraph to the next cell
                cellPara = row.Cells[1].AddParagraph();
                row.Cells[1].CellFormat.Borders.BorderType = BorderStyle.None;
                row.Cells[1].CellFormat.Borders.Color = Syncfusion.Drawing.Color.FromArgb(255, 255, 255);
                row.Cells[1].CellFormat.VerticalAlignment = VerticalAlignment.Middle;
                row.Cells[1].CellFormat.BackColor = Syncfusion.Drawing.Color.FromArgb(255, 255, 255);
                //Appends the text
                txt = cellPara.AppendText("");
                cellPara.ParagraphFormat.HorizontalAlignment = HorizontalAlignment.Center;
                row.Cells[0].Width = 350;
                row.Cells[1].Width = 150;
                #endregion second row

                #endregion
                //Adds a new paragraph
                section.AddParagraph();

                paragraph = section.AddParagraph();

                string words = "Table 2: Summary of statistics as at:  " + _datatime;// DateTime.Now.ToString("dd") + ", " + DateTime.Now.DayOfWeek + ", " + DateTime.Now.ToString("MMMM") + " " + DateTime.Now.Year;
                txt = paragraph.AppendText(words);
                txt.CharacterFormat.TextColor = Syncfusion.Drawing.Color.FromArgb(192, 0, 0);
                txt.CharacterFormat.FontName = "Times New Roman";
                txt.CharacterFormat.Bold = true;
                txt.CharacterFormat.FontSize = 14f;
                section.AddParagraph();


                #region General Information
                //Adds a new table
                table = section.Body.AddTable();
                table.ResetCells((data.Count + 1), 4);
                row = table.Rows[0];
                row.Height = 20;
                row.Cells[0].Width = 30;
                //Adds a new paragraph

Views/Reports/CombinedSitRepReports.cshtml
@model CHMIS.ModelView.ReportsViewModel
@{
    ViewData["Title"] = "SitRep Reports";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<ol class="breadcrumb" style="margin-top:5px;">
    <li class="breadcrumb-item active" style="width: 100%; background-color: black; color: white; font-family: Cambria; padding: 5px; font: bolder;"> <stong> SitRep - Summary of statistics as at -  @System.DateTime.Now.ToLongDateString(). </stong></li>
</ol>
<form method="post" asp-controller="Reports" asp-action="CombinedExportSitRep">
    <div class="form-row">
        <div class="form-group col-md-5">
            <ejs-datepicker id="StartDate" cssClass="e-outline" max="DateTime.Now" format="yyyy/MM/dd" value="@System.DateTime.Today" placeholder="Date of Reporting" floatLabelType="Auto"></ejs-datepicker>
        </div>
        @*<div class="form-group col-md-5">
            <ejs-dropdownlist id="Division" cssClass="e-outline" dataSource="@ViewBag.division" placeholder="Division" filterBarPlaceholder="Search Division" allowFiltering="true" floatLabelType="Auto" popupHeight="300px">
                <e-dropdownlist-fields text="CountyName" value="CountyId"></e-dropdownlist-fields>
            </ejs-dropdownlist>
        </div>*@
        <div class="form-group col-md-3">
            <button type="submit" class="btn btn-danger e-btn-medium" style="margin-top:10px;">Generate Combined SitRep Report</button>
        </div>
    </div>
</form>

Views/Reports/SitRepReports.cshtml
@model CHMIS.ModelView.ReportsViewModel
@{
    ViewData["Title"] = "SitRep Reports";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<ol class="breadcrumb" style="margin-top:5px;">
    <li class="breadcrumb-item active" style="width: 100%; background-color: black; color: white; font-family: Cambria; padding: 5px; font: bolder;"> <stong> SitRep - Summary of statistics as at -  @System.DateTime.Now.ToLongDateString(). </stong></li>
</ol>
<form method="post" asp-controller="Reports" asp-action="WordExportSitRep">
    <div class="form-row">
        <div class="form-group col-md-5">
            <ejs-datepicker id="StartDate" cssClass="e-outline" max="DateTime.Now" format="yyyy/MM/dd" value="@System.DateTime.Today" placeholder="Date of Reporting" floatLabelType="Auto"></ejs-datepicker>
        </div>
        <div class="form-group col-md-5">
            <ejs-dropdownlist id="Division" cssClass="e-outline" dataSource="@ViewBag.division" placeholder="Division" filterBarPlaceholder="Search Division" allowFiltering="true" floatLabelType="Auto" popupHeight="300px">
                <e-dropdownlist-fields text="CountyName" value="CountyId"></e-dropdownlist-fields>
            </ejs-dropdownlist>
        </div>
        <div class="form-group col-md-2">
            <button type="submit" class="btn btn-danger e-btn-medium" style="margin-top:10px;">Generate SitRep Report</button>
        </div>
    </div>
</form>