Controllers/UtilitiesController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using CHMIS.BLL;
using CHMIS.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Syncfusion.EJ2.Base;

namespace CHMIS.Controllers
{
    public class UtilitiesController : Controller
    {
        private IWebHostEnvironment hostingEnv;
        private CHMISContext context;
        private IUserService userInfor;

        public UtilitiesController(CHMISContext Context, IWebHostEnvironment env, IUserService _userinfo)

        {
            this.hostingEnv = env;
            this.context = Context;
            this.userInfor = _userinfo;
        }

        public IActionResult Index()
        {
            return View();
        }

        #region Country
        public IActionResult Country()
        {

            return View();
        }

        public IActionResult AddCountryPartial([FromBody] CRUDModel<ACountry> value)
        {
           

            return PartialView("_DialogCountryAddPartial", value.Value);
        }

        public ActionResult EditCountryPartial([FromBody] CRUDModel<ACountry> value)
       
        {
           
            return PartialView(value.Value);
        }
              
        public ActionResult CountryDataSource([FromBody] DataManagerRequest dm)
        {

            var _data = context.ACountry.AsNoTracking().OrderByDescending(o => o.CountryCode).ToList();
            IEnumerable data = _data;
            int count = _data.Count(); 

            DataOperations operation = new DataOperations();
            //Performing filtering operation
            if (dm.Where != null)
            {
                data = operation.PerformFiltering(data, dm.Where, "and");
                var filtered = (IEnumerable<object>)data;
                count = filtered.Count();
            }
            //Performing search operation
            if (dm.Search != null)
            {
                data = operation.PerformSearching(data, dm.Search);
                var searched = (IEnumerable<object>)data;
                count = searched.Count();
            }
            //Performing sorting operation
            if (dm.Sorted != null)
                data = operation.PerformSorting(data, dm.Sorted);

            //Performing paging operations
            if (dm.Skip > 0)
                data = operation.PerformSkip(data, dm.Skip);
            if (dm.Take > 0)
                data = operation.PerformTake(data, dm.Take);

            return Json(new { result = data, count = count }, new Newtonsoft.Json.JsonSerializerSettings());
        }
               
        public int CheckCountryCode()
        {
            var councode = context.ACountry.OrderByDescending(o => o.CountryId).Take(1).Select(f => f.CountryId).FirstOrDefault();
            return (Convert.ToInt32(councode));
        }

        public ActionResult DialogInsert([FromBody] CRUDModel<ACountry> value)
        {
            string result = string.Empty;

            ACountry _table = context.ACountry.FirstOrDefault(o =>
            ((o.CountryCode == value.Value.CountryCode) && (o.CountryId == value.Value.CountryId)));
            
            if (_table == null)
            {
                //Save into ACountry table
                ACountry table = new ACountry();

                if (string.IsNullOrEmpty(table.CountryId.ToString()) || table.CountryId == 0)
                {
                    var newCode = CheckCountryCode();
                    table.CountryId = ++newCode; //Save Country ID
                }
                
                table.CountryCode = value.Value.CountryCode;
               // table.CountryId = value.Value.CountryId;
                table.CountryName = value.Value.CountryName;
                
                context.ACountry.Add(table);
                context.SaveChanges();

            }
            else
            {
                this.DialogUpdate(value);
            }
            return Json(value.Value);
        }


        // Update using Table CoreCaseContacts
        public ActionResult DialogUpdate([FromBody] CRUDModel<ACountry> value)
        {
            ACountry table = context.ACountry.FirstOrDefault(o =>
            ((o.CountryCode == value.Value.CountryCode) && (o.CountryId == value.Value.CountryId)));


            if (table != null)
            {
                //table.CountryCode = value.Value.CountryCode;
                table.CountryId = value.Value.CountryId;
                table.CountryName = value.Value.CountryName;

                context.Entry(table).CurrentValues.SetValues(value);
                context.Entry(table).State = EntityState.Modified;

                context.SaveChanges();

                try
                {

                    TempData["Success"] = "Record Saved Successfully!";
                }

              

                catch (DbEntityValidationException dbEx)
                {
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            TempData["Success"] += string.Format("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                            System.Console.WriteLine("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                        }
                    }
                }
            }
            else
            {
                this.DialogInsert(value);
            }

            return Json(value.Value);
        }

        #endregion Country

        #region Region
        public IActionResult Region()
        {

            return View();
        }

        public ActionResult RegionDataSource([FromBody] DataManagerRequest dm)
        {

            var _data = context.ARegion.AsNoTracking().OrderByDescending(o => o.RegionId).ToList();
            IEnumerable data = _data;
            int count = _data.Count();

            DataOperations operation = new DataOperations();
            //Performing filtering operation
            if (dm.Where != null)
            {
                data = operation.PerformFiltering(data, dm.Where, "and");
                var filtered = (IEnumerable<object>)data;
                count = filtered.Count();
            }
            //Performing search operation
            if (dm.Search != null)
            {
                data = operation.PerformSearching(data, dm.Search);
                var searched = (IEnumerable<object>)data;
                count = searched.Count();
            }
            //Performing sorting operation
            if (dm.Sorted != null)
                data = operation.PerformSorting(data, dm.Sorted);

            //Performing paging operations
            if (dm.Skip > 0)
                data = operation.PerformSkip(data, dm.Skip);
            if (dm.Take > 0)
                data = operation.PerformTake(data, dm.Take);

            return Json(new { result = data, count = count }, new Newtonsoft.Json.JsonSerializerSettings());
        }

        public IActionResult AddRegionPartial([FromBody] CRUDModel<ARegion> value)
        {


            return PartialView("_DialogRegionAddPartial", value.Value);
        }

        public ActionResult EditRegionPartial([FromBody] CRUDModel<ARegion> value)

        {

            return PartialView(value.Value);
        }

        public string CheckRegionCode()
        {
            string code = "0";
            int result = 0;
            result = context.ARegion.ToList().Count();
            code += (result + 1);
            var x = new ARegion()
            {
                RegionId = code
            };

            return (code);
        }

        //Insert into Region Table
        public ActionResult DialogInsertRegion([FromBody] CRUDModel<ARegion> value)
        {
            string result = string.Empty;

            ARegion _table = context.ARegion.FirstOrDefault(o =>
            (o.RegionId == value.Value.RegionId));

            if (_table == null)
            {
                //Save into ACountry table
                ARegion table = new ARegion();

                table.RegionId = CheckRegionCode();
                table.RegionName = value.Value.RegionName;
               
                context.ARegion.Add(table);
                context.SaveChanges();

            }
            else
            {
                this.DialogUpdateRegion(value);
            }
            return Json(value.Value);
        }


        // Update using Table CoreCaseContacts
        public ActionResult DialogUpdateRegion([FromBody] CRUDModel<ARegion> value)
        {
            ARegion table = context.ARegion.FirstOrDefault(o =>
            (o.RegionId == value.Value.RegionId));

            if (table != null)
            {
                table.RegionName = value.Value.RegionName;

                context.Entry(table).CurrentValues.SetValues(value);
                context.Entry(table).State = EntityState.Modified;

                context.SaveChanges();

                try
                {

                    TempData["Success"] = "Record Saved Successfully!";
                }



                catch (DbEntityValidationException dbEx)
                {
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {

Views/Utilities/County.cshtml
@{
    ViewData["Title"] = "County";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb" style="margin-top:5px;">
    @*<li class="breadcrumb-item">
        <a href="/DashBoard/Dashboard">Dashboard</a>
    </li>*@
    <li class="breadcrumb-item active" style="width:100%; background-color: black; color:white; font-family:Cambria; padding:5px; font:bolder">Add/Edit - County</li>
</ol>
@*<partial name="MessagePartial" />*@
<ejs-grid id="MainGrid"
           allowPaging="true" allowResizing="true" allowTextWrap="true" gridLines="Both"
          allowSorting="true" allowReordering="true" allowGrouping="true" showColumnChooser="true"
          toolbar="@(new List<string>() { "Search", "Add", "Edit", "Delete","Update","Cancel" , "ExcelExport" , "CsvExport" ,"PdfExport","ColumnChooser"})"
          allowFiltering="true" allowSelection="true" allowExcelExport="true"
          allowPdfExport="true" toolbarClick="toolbarClick" actionComplete="onEdit" actionBegin="OnBegin" load="onLoad">

    <e-data-manager url="/Utilities/CountyDataSource" insertUrl="/Utilities/DialogInsertCounty" updateUrl="/Utilities/DialogUpdateCounty" adaptor="UrlAdaptor"></e-data-manager>

    <e-grid-pagesettings pageSize="7" pageSizes="true" pageCount="4"/>
    <e-grid-filterSettings type="Excel"></e-grid-filterSettings>
    <e-grid-editSettings allowAdding="true" allowDeleting="true" allowEditing="true" mode="Dialog" template='#dialogtemplate'></e-grid-editSettings>
    <e-grid-selectionsettings type="Single"></e-grid-selectionsettings>
    <e-grid-columns>
        <e-grid-column type="checkbox" width="50"></e-grid-column>
        <e-grid-column field="CountyId" width="280" headerText="County ID" visible="false" isPrimaryKey="true" isIdentity="true"></e-grid-column>
        <e-grid-column field="DistrictId" headerText="District" foreignKeyField="DistrictId" foreignKeyValue="DistrictName" dataSource="@ViewBag.district"></e-grid-column>
        <e-grid-column field="CountyName" headerText="County" allowEditing="false" visible="true"></e-grid-column>
        
    </e-grid-columns>
</ejs-grid>

<script>
    function onLoad(args) {
        setToolbarItemsAdmin();
    }
    function toolbarClick(args) {
        if (args.item.id === this.element.id + '_pdfexport') {
            this.pdfExport();
        }
        if (args.item.id === this.element.id + '_csvexport') {
            this.csvExport();
        }
        if (args.item.id === this.element.id + '_excelexport') {
            this.excelExport();
        }
    }


    function onEdit(args) {
        if (args.requestType === 'beginEdit' || args.requestType === 'add') {
            let spinner = ej.popups.createSpinner({ target: args.dialog.element });
            //ej.popups.showSpinner(args.dialog.element);

            //#####
           var data = args.rowData;

            window.args = args.requestType;

            // For custom save button
            args.dialog.btnObj[0].destroy();
            args.dialog.btnObj[0].element.id = "save";

            var progressSaveButton = new ejs.splitbuttons.ProgressButton({
                content: 'Save',
                enableProgress: true,
                animationSettings: { effect: 'SlideRight' },
                spinSettings: { position: 'Center' },
                cssClass: 'e-success',
            }); progressSaveButton.appendTo('#save');

            // For custom cancel button
            args.dialog.btnObj[1].destroy();
            args.dialog.btnObj[1].element.id = "cancel";

            var progressCancelButton = new ejs.splitbuttons.ProgressButton({
                content: 'Cancel',
                enableProgress: true,
                animationSettings: { effect: 'SlideRight' },
                spinSettings: { position: 'Center' },
                cssClass: 'e-danger',

            });
            progressCancelButton.appendTo('#cancel');

            // saving the edit action
            document.getElementById('save').addEventListener('click', function (args) {
                //onclick = savess();
            }.bind(this));

            // Cancelling the edit action
            document.getElementById('cancel').addEventListener('click', function (args) {
                //onclick = cancelss();

            }.bind(this));

             //#####


            if (args.requestType === 'beginEdit') {

                args.dialog.header = args.requestType === 'beginEdit' ? 'Edit ' + args.rowData['CountyName'] : 'County';

                    var ajax = new ej.base.Ajax({
                        url: "@Url.Action("EditCountyPartial", "Utilities")", //render the partial view
                        type: "POST",
                        data: JSON.stringify({ value: args.rowData})
                    });
                    ajax.send().then(function (data) {
                        appendElement(data, args.form); //Render the edit form with selected record
                        args.form.elements.namedItem('CountyId').focus();
                        ej.popups.hideSpinner(args.dialog.element);

                    }).catch(function (xhr) {
                        console.log(xhr);
                        ej.popups.hideSpinner(args.dialog.element);
                    });
                }

            if (args.requestType === 'add') {

                args.dialog.header = 'Add a County'

                  var ajax = new ej.base.Ajax({
                        url: "@Url.Action("AddCountyPartial", "Utilities")", //render the partial view
                        type: "POST",
                        contentType: "application/json",
                        data: JSON.stringify({ value: args.rowData})
                    });
                    ajax.send().then(function (data) {
                        appendElement(data, args.form); //Render the edit form with selected record
                        args.form.elements.namedItem('CountyId').focus();
                        ej.popups.hideSpinner(args.dialog.element);

                    }).catch(function (xhr) {
                        console.log(xhr);
                        ej.popups.hideSpinner(args.dialog.element);
                    });
                }
        }
        else if(args.requestType=="save") {
             var grid = document.getElementById("MainGrid").ej2_instances[0];
              grid.refresh(); // refresh the Grid.
         }
    }

    function appendElement(elementString, form) {
            form.querySelector("#dialogTemp").innerHTML = elementString;
            var script = document.createElement('script');
            script.type = "text/javascript";
            var serverScript = form.querySelector("#dialogTemp").querySelector('script');
            script.textContent = serverScript.innerHTML;
            document.head.appendChild(script);
            serverScript.remove();
    }

      function OnBegin(args) {
          if (args.requestType == 'save') {
    
              var discode = document.getElementById("DistrictId").ej2_instances[0];
              var discodevalue = discode.value;

              var couname = document.getElementById("CountyName").ej2_instances[0];
              var counamevalue = couname.value;


              if ((discodevalue == null || discodevalue == "0" || discodevalue == "" || discodevalue == " ")
              &&(counamevalue == null || counamevalue == "0" || counamevalue == "" || counamevalue == " ")) {

                 alert("Please select a district and enter a county name")
                 args.cancel = true;
              }

               else if ((discodevalue == null || discodevalue == "0" || discodevalue == "" || discodevalue == " ")) {

                 alert("Please select a district")
                 args.cancel = true;
              }

               else if ((counamevalue == null || counamevalue == "0" || counamevalue == "" || counamevalue == " ")) {

                 alert("Please enter a county")
                 args.cancel = true;
              }

        }
    }

</script>


<script id='dialogtemplate' type="text/x-template">
    <div id="dialogTemp">
    </div>
</script>
<style type="text/css">
</style>

@*Change size of the add and edit dialog*@

<style>
    #MainGrid_dialogEdit_wrapper {
        min-height: 400px;
        min-width: 50%;
    }
</style>
<script>
     function setToolbarItems()
     {
            //Gets the ToolBar.
            var myRoleIsinKCCA = "@User.IsInRole("KCCA General")";
            var myRoleIsinViewer = "@User.IsInRole("Viewer")";

         if (myRoleIsinKCCA.toUpperCase() == 'TRUE' || myRoleIsinViewer.toUpperCase() == 'TRUE'){
             var gridObj = document.getElementById('Grid').ej2_instances[0];
             gridObj.toolbarSettings = { showToolbar: true, toolbarItems: ["search"] };
             gridObj.editSettings = { allowEditing: false, allowAdding: false, allowDeleting: false };

                return;

                var $toolbar = $("#Grid_toolbarItems");
                ////Gets the tool

                li = $("#Grid_excelExport");
                $toolbar.ejToolbar("disableItem", li);

                li = $("#Grid_wordExport");
                $toolbar.ejToolbar("disableItem", li);

                li = $("#Grid_pdfExport");
                $toolbar.ejToolbar("disableItem", li);
         }
    }
      function setToolbarItemsChild()
      {
            //Gets the ToolBar.
            var myRoleIsinKCCA = "@User.IsInRole("KCCA General")";
            var myRoleIsinViewer = "@User.IsInRole("Viewer")";

          if (myRoleIsinKCCA.toUpperCase() == 'TRUE' || myRoleIsinViewer.toUpperCase() == 'TRUE') {
              //debugger;
             var gridObj = this; //document.getElementById('childGrid').ej2_instances[0];
              gridObj.toolbar = { showToolbar: true, toolbarItems: ["search"] };
             gridObj.editSettings = { allowEditing: false, allowAdding: false, allowDeleting: false };

             //var grid = $("#childGrid").ejGrid({
             //       //  editSettings: { allowDeleting: true },
             //       toolbarSettings: { showToolbar: true, toolbarItems: ["search"] }  ,
             //       editSettings: { allowEditing: false, allowAdding: false, allowDeleting: false },
             //   });

                return;

              var $toolbar = $("#" +gridObj + "_toolbarItems");
                ////Gets the tool

              li = $("#" +gridObj + "_excelExport");
                $toolbar.ejToolbar("disableItem", li);

              li = $("#" +gridObj + "_wordExport");
                $toolbar.ejToolbar("disableItem", li);

              li = $("#" + gridObj + "_pdfExport");
                $toolbar.ejToolbar("disableItem", li);
         }
    }

    function setToolbarItemsAdmin()
     {
            //Gets the ToolBar.
            var myRoleIsinKCCA = "@User.IsInRole("KCCA General")";
            var myRoleIsinViewer = "@User.IsInRole("Viewer")";

         if (myRoleIsinKCCA.toUpperCase() == 'TRUE' || myRoleIsinViewer.toUpperCase() == 'TRUE'){
             var gridObj = document.getElementById('MainGrid').ej2_instances[0];
             gridObj.toolbarSettings = { showToolbar: true, toolbarItems: ["search"] };
             gridObj.editSettings = { allowEditing: false, allowAdding: false, allowDeleting: false };

                return;

             var $toolbar = $("#MainGrid_toolbarItems");
                ////Gets the tool

             li = $("#MainGrid_excelExport");
                $toolbar.ejToolbar("disableItem", li);

             li = $("#MainGrid_wordExport");
                $toolbar.ejToolbar("disableItem", li);

             li = $("#MainGrid_pdfExport");
                $toolbar.ejToolbar("disableItem", li);
         }
    }
</script>

Views/Utilities/EditCountyPartial.cshtml
@*EditDistrictPartial*@

@model CHMIS.Models.ACounty
@using Syncfusion.EJ2

<div id="defaultTab" style="width: 100%; padding-left:3%; padding-right:3%">

    <div class="panel-group" id="accordion">

        <div class="panel panel-default" id="complainant_Details">
            <div class="panel-heading">
                <h5 style="width:100%; background-color: cadetblue; color:white; font-family:Cambria; padding:5px;" class="panel-title ">
                    <a data-toggle="collapse" class="dialogClass" data-parent="#accordion" href="#collapse2">
                        County Module
                    </a>
                </h5>
            </div>

            <br /><br />

            @*<div id="collapse2" class="panel-collapse collapse in">*@
            <div class="panel-body">
                <div class="row material2">

                    <div class="col-xs-6 col-sm-6 col-lg-6 col-md-6">
                        <ejs-dropdownlist id="DistrictId" cssClass="e-outline" enabled="true" value="@Model.DistrictId" dataSource="@ViewBag.district" floatLabelType="Auto" placeholder="Choose a District" allowFiltering="true" filterBarPlaceholder="Select a District" popupHeight="300px">
                            <e-dropdownlist-fields text="DistrictName" value="DistrictId"></e-dropdownlist-fields>
                        </ejs-dropdownlist>
                    </div>

                    <div class="col-xs-6 col-sm-6 col-lg-6 col-md-6">
                        <ejs-textbox id="CountyName" asp-for="CountyName" cssClass="e-outline" placeholder="County Name" floatLabelType="Auto" name="CountyName" type='text' value="@Model.CountyName"></ejs-textbox>
                    </div>
                </div>

                <hr />

                <div class="row material2" hidden>
                    <div class="col-xs-6 col-sm-6 col-lg-6 col-md-6">
                        <ejs-textbox id="CountyId" asp-for="CountyId" cssClass="e-outline" placeholder="County ID" disabled floatLabelType="Auto" name="CountyId" type='text' value="@Model.CountyId"></ejs-textbox>
                    </div>
                </div>


            </div>

            @*</div>*@
        </div>
    </div>
</div>
<ejs-scripts></ejs-scripts>
<script>
    function onFileRemove(args) {
        args.postRawFile = false;
    }
    //var dropElement = document.getElementsByClassName('control-fluid')[0];
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}


<style>
    .dialogClass {
        color: white;
    }
</style>
<style>
    .panel-default > .panel-heading {
        background-color: #56ad61;
        color: white;
    }
</style>

Views/Utilities/EditDistrictPartial.cshtml
@*EditDistrictPartial*@

@model CHMIS.Models.ADistrict
@using Syncfusion.EJ2

<div id="defaultTab" style="width: 100%; padding-left:3%; padding-right:3%">

    <div class="panel-group" id="accordion">

        <div class="panel panel-default" id="complainant_Details">
            <div class="panel-heading">
                <h5 style="width:100%; background-color: cadetblue; color:white; font-family:Cambria; padding:5px;" class="panel-title ">
                    <a data-toggle="collapse" class="dialogClass" data-parent="#accordion" href="#collapse2">
                        District Module
                    </a>
                </h5>
            </div>

            <br /><br />

            @*<div id="collapse2" class="panel-collapse collapse in">*@
            <div class="panel-body">
                <div class="row material2">

                    <div class="col-xs-6 col-sm-6 col-lg-6 col-md-6">
                        <ejs-dropdownlist id="RegionId" cssClass="e-outline" enabled="true" value="@Model.RegionId" dataSource="@ViewBag.region" floatLabelType="Auto" placeholder="Choose a Region" allowFiltering="true" filterBarPlaceholder="Select a Region" popupHeight="300px">
                            <e-dropdownlist-fields text="RegionName" value="RegionId"></e-dropdownlist-fields>
                        </ejs-dropdownlist>
                    </div>

                    <div class="col-xs-6 col-sm-6 col-lg-6 col-md-6">
                        <ejs-textbox id="DistrictName" asp-for="DistrictName" cssClass="e-outline" placeholder="District Name" floatLabelType="Auto" name="DistrictName" type='text' value="@Model.DistrictName"></ejs-textbox>
                    </div>

                </div>

                <hr />

                <div class="row material2" @*hidden*@>
                    <div class="col-xs-6 col-sm-6 col-lg-6 col-md-6">
                        <ejs-textbox id="DistrictId" asp-for="DistrictId" cssClass="e-outline" placeholder="District ID" disabled floatLabelType="Auto" name="DistrictId" type='text' value="@Model.DistrictId"></ejs-textbox>
                    </div>
                </div>


            </div>

            @*</div>*@
        </div>
    </div>
</div>
<ejs-scripts></ejs-scripts>
<script>
    function onFileRemove(args) {
        args.postRawFile = false;
    }
    //var dropElement = document.getElementsByClassName('control-fluid')[0];
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<style>
    .dialogClass {
        color: white;
    }
</style>
<style>
    .panel-default > .panel-heading {
        background-color: #56ad61;
        color: white;
    }
</style>

Views/Utilities/EditOperationalAreaPartial.cshtml
@*EditOperationalAreaPartial*@

@model CHMIS.Models.AOperationalArea
@using Syncfusion.EJ2

<div id="defaultTab" style="width: 100%; padding-left:3%; padding-right:3%">

    <div class="panel-group" id="accordion">

        <div class="panel panel-default" id="complainant_Details">
            <div class="panel-heading">
                <h5 style="width:100%; background-color: cadetblue; color:white; font-family:Cambria; padding:5px;" class="panel-title ">
                    <a data-toggle="collapse" class="dialogClass" data-parent="#accordion" href="#collapse2">
                        Operational Area Module
                    </a>
                </h5>
            </div>

            <br /><br />

            @*<div id="collapse2" class="panel-collapse collapse in">*@
            <div class="panel-body">
                <div class="row material2">

                    <div class="col-xs-6 col-sm-6 col-lg-6 col-md-6">
                        <ejs-textbox id="OperationalArea" asp-for="OperationalArea" cssClass="e-outline" placeholder="Operational Area" floatLabelType="Auto" name="OperationalArea" type='text' value="@Model.OperationalArea"></ejs-textbox>
                    </div>

                </div>

                <hr />

                <div class="row material2">

                    <div class="col-xs-6 col-sm-6 col-lg-6 col-md-6" hidden>
                        <ejs-textbox id="OperationalCode" asp-for="OperationalCode" cssClass="e-outline" placeholder="Operational Code" disabled floatLabelType="Auto" name="OperationalCode" type='text' value="@Model.OperationalCode"></ejs-textbox>
                    </div>

                </div>
            </div>

            @*</div>*@
        </div>
    </div>
</div>
<ejs-scripts></ejs-scripts>
<script>
    function onFileRemove(args) {
        args.postRawFile = false;
    }
    //var dropElement = document.getElementsByClassName('control-fluid')[0];
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<style>
    .dialogClass {
        color: white;
    }
</style>
<style>
    .panel-default > .panel-heading {
        background-color: #56ad61;
        color: white;
    }
</style>

Views/Utilities/_DialogRegionAddPartial.cshtml
@*CountryAddPartial*@

@model CHMIS.Models.ARegion
@using Syncfusion.EJ2

<div id="defaultTab" style="width: 100%; padding-left:3%; padding-right:3%">

    <div class="panel-group" id="accordion">

        <div class="panel panel-default" id="complainant_Details">
            <div class="panel-heading">
                <h5 style="width:100%; background-color: cadetblue; color:white; font-family:Cambria; padding:5px;" class="panel-title ">
                    <a data-toggle="collapse" class="dialogClass" data-parent="#accordion" href="#collapse2">
                        Region Module
                    </a>
                </h5>
            </div>

            <br /><br />

            @*<div id="collapse2" class="panel-collapse collapse in">*@
            <div class="panel-body">
                <div class="row material2">

                    <div class="col-xs-6 col-sm-6 col-lg-6 col-md-6">
                        <ejs-textbox id="RegionName" asp-for="RegionName" cssClass="e-outline" placeholder="Region Name" floatLabelType="Auto" name="RegionName" type='text' value="@Model.RegionName"></ejs-textbox>
                    </div>

                </div>

                <hr />

                <div class="row material2" hidden>
                    <div class="col-xs-6 col-sm-6 col-lg-6 col-md-6">
                        <ejs-textbox id="RegionId" asp-for="RegionId" cssClass="e-outline" placeholder="Region ID" disabled floatLabelType="Auto" name="RegionId" type='text' value="@Model.RegionId"></ejs-textbox>
                    </div>
                </div>


            </div>

            @*</div>*@
        </div>
    </div>

</div>

<ejs-scripts></ejs-scripts>
<script>
    function onFileRemove(args) {
        args.postRawFile = false;
    }
    //var dropElement = document.getElementsByClassName('control-fluid')[0];
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}


<style>
    .dialogClass {
        color: white;
    }
</style>
<style>
    .panel-default > .panel-heading {
        background-color: #56ad61;
        color: white;
    }
</style>